### ISSUE TITLE
Getting Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by webciter** [IBM/MAX-Image-Resolution-Enhancer#23]
Unable to init API, sudo docker run -it -p 5000:5000 codait/max-image-resolution-enhancer

returns Illegal instruction (core dumped)

using ubuntu 19.10 and Docker version 19.03.3, build a872fc2f86

**Comment by xuhdev** [comment]
Could you paste the output of `uname -a`?

**Comment by webciter** [comment]
figured out the problem, it was the cpu extensions.

**Comment by xuhdev** [comment]
Could you provide more details?

**Comment by kiki67100** [comment]
@xuhdev I think is related to https://tech.amikelive.com/node-887/how-to-resolve-error-illegal-instruction-core-dumped-when-running-import-tensorflow-in-a-python-program/

I have the same issue, it's because new version of tensorflow is not built with goodl instruction for old cpu
