### ISSUE TITLE
/model/metadata returns unexpected results

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Image-Resolution-Enhancer#3]
```
{
  "id": "srgan_tensorflow",
  "name": "Super-Resolution Generative Adversarial Network (SRGAN)",
  "description": "SRGAN trained on the OpenImagesV4 dataset.",
  "type": "Image-To-Image Translation Or Transformation",
  "source": "https://developer.ibm.com/exchanges/models",
  "license": "ApacheV2"
}
```

Issues:
 - source URL is incorrect (should point to https://developer.ibm.com/exchanges/models/all/max-text-sentiment-classifier/)
 - license name doesn't meet standard
 - id naming convention doesn't meet standard

**Comment by splovyt** [comment]
Fixed in https://github.com/IBM/MAX-Image-Resolution-Enhancer/commit/fc0fad3fe0d5666b6def551d3e4f680449d87a93

Thanks @ptitzler
