### ISSUE TITLE
Edit - Misleading documentation 

### ISSUE THREAD

**Issue by jddunn** [IBM/MAX-Image-Resolution-Enhancer#31]
![401bea09-6081-47aa-9a9e-7e33460e058e](https://user-images.githubusercontent.com/11220853/93010296-203d3c80-f559-11ea-9e97-b2d1a5300763.png)

Attached is a screenshot of the "enhanced" result taken from the example image using the API provided here `http://max-image-resolution-enhancer.codait-prod-41208c73af8fca213512856c7a09db52-0000.us-east.containers.appdomain.cloud/`. While it may work for increasing resolution size it's clearly a misleading example, and doesn't do anything to deblur or reconstruct image details. Why falsely advertise?

**Comment by jddunn** [comment]
Sorry to raise this issue, it's not a bug, but the documentation seems slightly misleading. Yes this does upscale low-resolution images, but "generating photo-realistic details" is  stretch. This model doesn't work to reconstruct meaningful details not captured in the original photo.

**Comment by roark** [comment]
For what it's worth the following is the enhancement I got from running it locally within a Docker image. You can see the actual enhanced details in the upscaling. I'm not a contributor to the project, so have no understanding what the reasoning behind the difference might be, but it does appear to work for me.
![food_high_res](https://user-images.githubusercontent.com/120450/132159959-0fbe3194-b354-45ea-a43f-dfe7f6d3f1ec.png)
