### ISSUE TITLE
Docker build fails on Windows 10

### ISSUE THREAD

**Issue by Zod20** [IBM/MAX-Image-Resolution-Enhancer#35]
> [7/7] RUN sha512sum -c sha512sums.txt:
#11 0.809 sha512sum: 'assets/SRGAN/model.data-00000-of-00001'$'\r': No such file or directory
#11 0.809 sha512sum: 'assets/SRGAN/model.index'$'\r': No such file or directory
#11 0.809 sha512sum: 'assets/SRGAN/model.meta'$'\r': No such file or directory
#11 0.809 sha512sum: WARNING: 3 listed files could not be read
: FAILED open or readN/model.data-00000-of-00001
: FAILED open or readN/model.index
: FAILED open or readN/model.meta
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c sha512sum -c sha512sums.txt]: runc did not terminate sucessfully

**Comment by bdwyer2** [comment]
Hi @Zod20, looks like you have an issue with your git configuration.

You can either run `git config --global core.autocrlf false` or just comment out the `RUN sha512sum -c sha512sums.txt` line in the Dockerfile.

See this issue for further: https://github.com/IBM/MAX-Audio-Classifier/issues/60

**Comment by Zod20** [comment]
> Hi @Zod20, looks like you have an issue with your git configuration.
> 
> You can either run `git config --global core.autocrlf false` or just comment out the `RUN sha512sum -c sha512sums.txt` line in the Dockerfile.
> 
> See this issue for further: [IBM/MAX-Audio-Classifier#60](https://github.com/IBM/MAX-Audio-Classifier/issues/60)

Thanks, I commented out the RUN line in Dockerfile and it worked :D
