### ISSUE TITLE
wget: unable to resolve host address ‘max-cdn.cdn.appdomain.cloud’

### ISSUE THREAD

**Issue by cristiangutie** [IBM/MAX-Image-Resolution-Enhancer#37]
Hello,
I'm getting this error while trying to build from the Docker file. Is this a temporary issue or the project its not not maintained anymore?

Best regards, 
Cristián G.

**Comment by bdwyer2** [comment]
Hi @cristiangutie

What is the exact error you are getting? Trouble resolving the domain?

Are you able to download the file directly from your computer (https://max-cdn.cdn.appdomain.cloud/max-image-resolution-enhancer/1.0.0/assets.tar.gz)?

If for some reason you are still unable to use the CDN URL you can download the file directly from our object storage by changing line 10 in the docker file to point to `s3.us.cloud-object-storage.appdomain.cloud/codait-cos-max/max-image-resolution-enhancer/1.0.0`

**Comment by cristiangutie** [comment]
Hi @bdwyer2 

Thank you for your prompt reply I really appreciate it.

I'm still getting the error. I'm using Fedora 32.

> Sending build context to Docker daemon  16.36MB
> Step 1/11 : FROM quay.io/codait/max-base:v1.3.2
>  ---> 9ef8bb15eab9
> Step 2/11 : ARG model_bucket=s3.us.cloud-object-storage.appdomain.cloud/codait-cos-max/max-image-resolution-enhancer/1.0.0
>  ---> Running in 55c2993100e1
> Removing intermediate container 55c2993100e1
>  ---> 1910cb12a47c
> Step 3/11 : ARG model_file=assets.tar.gz
>  ---> Running in 23ef29d59f31
> Removing intermediate container 23ef29d59f31
>  ---> 8be81977d781
> Step 4/11 : WORKDIR /workspace
>  ---> Running in 792f50db47da
> Removing intermediate container 792f50db47da
>  ---> bdb4a9fcdec7
> Step 5/11 : RUN wget -nv --show-progress --progress=bar:force:noscroll ${model_bucket}/${model_file} --output-document=assets/${model_file} &&   tar -x -C assets/ -f assets/${model_file} -v && rm assets/${model_file}
>  ---> Running in 35ce0c6c28e8
> wget: unable to resolve host address ‘s3.us.cloud-object-storage.appdomain.cloud’
> The command '/bin/sh -c wget -nv --show-progress --progress=bar:force:noscroll ${model_bucket}/${model_file} --output-document=assets/${model_file} &&   tar -x -C assets/ -f assets/${model_file} -v && rm assets/${model_file}' returned a non-zero code: 4

The weird thing is that using the browser or running the wget command alone with the CDN or the original URL works. 

Best Regards,
Cristián

**Comment by bdwyer2** [comment]
Looks like a DNS issue with your Docker setup. Are you on Ubuntu? If so did you follow the DNS instructions after installing Docker? https://docs.docker.com/engine/install/linux-postinstall/#specify-dns-servers-for-docker

**Comment by bdwyer2** [comment]
https://github.com/moby/moby/issues/16600#issuecomment-405966534

**Comment by xuhdev** [comment]
Seems like it's potentially a firewall configuration issue. Could you try the solution here? https://nts.strzibny.name/fedora-32-docker-dns/

**Comment by cristiangutie** [comment]
@xuhdev @bdwyer2 Thank you both very much for your help! 

@xuhdev The solution you shared did the trick.
