### ISSUE TITLE
Support Apple Silicon Processor

### ISSUE THREAD

**Issue by mezhevikin** [IBM/MAX-Image-Resolution-Enhancer#43]
Hi. I try run Enhancer on Mac Book Air M1, but I'm getting an error:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2021-03-30 14:41:04.891048: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted
```

**Comment by bdwyer2** [comment]
Hi @mezhevikin 

I don't currently have an arm machine to test on but you can try changing line # 17 in the Dockerfile to this:
```docker pull quay.io/codait/max-base:arm-arm32v7-latest```

You may also need to change the tensorflow version in the `requirements.txt` file if there in not a tensorflow build for your CPU. See this issue for more info https://github.com/IBM/MAX-Object-Detector/issues/72#issuecomment-552678944

**Comment by bdwyer2** [comment]
I opened PR #44 to work on this

**Comment by fharper** [comment]
> See this issue for more info [IBM/MAX-Object-Detector#72 (comment)](https://github.com/IBM/MAX-Object-Detector/issues/72#issuecomment-552678944)

Unfortunately, TensorFlow still doesn't support M1 chipset (arm64/ARMv8).

**Comment by fharper** [comment]
@mezhevikin is this fixed? @bdwyer2 PR isn't merged yet.

**Comment by bdwyer2** [comment]
Hi @fharper, I am no longer involved with this project. Maybe @kmh4321 can provide an update?
