### ISSUE TITLE
#5 0.811 wget: unable to resolve host address ‘max-cdn.cdn.appdomain.cloud’

### ISSUE THREAD

**Issue by zaizou** [IBM/MAX-Image-Resolution-Enhancer#54]
Hi,
At 
"
RUN wget -nv --show-progress --progress=bar:force:noscroll ${model_bucket}/${model_file} --output-document=assets/${model_file} && \
  tar -x -C assets/ -f assets/${model_file} -v && rm assets/${model_file}
"
the process fail and shows the folloowing message  
"#5 0.811 wget: unable to resolve host address ‘max-cdn.cdn.appdomain.cloud’ "

![image](https://user-images.githubusercontent.com/8124554/149391555-b73437ac-0aeb-4983-8e61-68a743d20dce.png)

**Comment by Kristofp** [comment]
replace  max-cdn.cdn.appdomain.cloud/ with https://cloud.ibm.com/ in the Dockerfile

**Comment by mhwahdan** [comment]
Same issue

**Comment by AsessionGuy** [comment]
Same error for me while building docker image

**Comment by fharper** [comment]
I have the same issue, and I'm not being a firewall. To fix this, you can access the storage directly by changing line 19 of `Dockerfile` to `ARG model_bucket=https://s3.us.cloud-object-storage.appdomain.cloud/codait-cos-max/max-image-resolution-enhancer/1.0.0`

**Comment by kmh4321** [comment]
Thank you for your patience, this is now fixed in: 
https://github.com/IBM/MAX-Image-Resolution-Enhancer/pull/55
